version: '3.8'

services:
  app:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    env_file:
      - .env
    environment:
      - DB_HOST=mysql
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - APP_PORT=${APP_PORT}
      - APP_ENV=${APP_ENV}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - WEBHOOK_AUTH_KEY=${WEBHOOK_AUTH_KEY}
      - CRON_SCHEDULE=${CRON_SCHEDULE}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=128M --wait_timeout=28800
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_INIT_CONNECT: 'SET NAMES utf8mb4'
      MYSQL_CHARACTER_SET_SERVER: 'utf8mb4'
      MYSQL_COLLATION_SERVER: 'utf8mb4_unicode_ci'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u${DB_USER}", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    restart: unless-stopped

  redis:
    image: redis/redis-stack:latest
    ports:
      - "${REDIS_PORT}:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    networks:
      - app-network
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - app-network
    depends_on:
      mysql:
        condition: service_healthy
    logging:
      driver: "none"
    labels:
      - "prometheus.io.scrape=false"

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
  redis_data: 