FROM golang:1.21

WORKDIR /app

# Air'i yüklüyoruz (spesifik bir versiyon kullanarak)
RUN go install github.com/cosmtrek/air@v1.49.0

# Gerekli dosyaları kopyalıyoruz
COPY go.mod go.sum ./
RUN go mod download

# Projeyi kopyalıyoruz
COPY . .

# Başlangıç komutu
ENTRYPOINT ["air", "-c", ".air.toml"] 
