basePath: /api
definitions:
  handlers.CreateMessageRequest:
    properties:
      content:
        description: Mesaj içeriği
        example: Merhaba, siparişiniz hazırlanıyor.
        type: string
      phone:
        description: Telefon numarası
        example: "+905551234567"
        type: string
    type: object
  handlers.CronLogsResponse:
    properties:
      data:
        description: Cron logları
        items:
          $ref: '#/definitions/models.CronLog'
        type: array
      status:
        description: İşlem durumu
        example: success
        type: string
    type: object
  handlers.CronMessageResponse:
    properties:
      message:
        description: İşlem mesajı
        example: Cron başlatıldı
        type: string
      status:
        description: İşlem durumu
        example: success
        type: string
    type: object
  handlers.CronStatusResponse:
    properties:
      is_running:
        description: Cron job çalışma durumu
        example: true
        type: boolean
      status:
        description: İşlem durumu
        example: success
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      code:
        description: Hata kodu
        example: CONTENT_REQUIRED
        type: string
      message:
        description: Hata mesajı
        example: Content alanı zorunludur
        type: string
      status:
        description: İşlem durumu
        example: failed
        type: string
    type: object
  handlers.MessageResponse:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/models.Message'
        description: Mesaj verisi
      status:
        description: İşlem durumu
        example: success
        type: string
    type: object
  handlers.MessagesResponse:
    properties:
      data:
        description: Mesaj listesi
        items:
          $ref: '#/definitions/models.Message'
        type: array
      status:
        description: İşlem durumu
        example: success
        type: string
    type: object
  models.CronLog:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      message_ids:
        description: Comma separated message IDs
        type: string
      messages_count:
        type: integer
      operation:
        description: START, STOP, UPDATE
        type: string
      status:
        description: Success or Failure
        type: boolean
    type: object
  models.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      message_id:
        type: string
      phone:
        type: string
      status:
        type: boolean
      updated_at:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: destek@example.com
    name: API Destek
  description: Bu API, mesaj gönderme ve yönetme işlemleri için kullanılır.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Message API
  version: "1.0"
paths:
  /cron/logs:
    get:
      consumes:
      - application/json
      description: Cron job'ın çalışma loglarını getirir
      produces:
      - application/json
      responses:
        "200":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.CronLogsResponse'
        "500":
          description: Sunucu hatası
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Cron loglarını getir
      tags:
      - cron
  /cron/start:
    post:
      consumes:
      - application/json
      description: Mesaj gönderme cron job'ını başlatır
      produces:
      - application/json
      responses:
        "200":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.CronMessageResponse'
        "500":
          description: Sunucu hatası
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Cron job'ı başlat
      tags:
      - cron
  /cron/status:
    get:
      consumes:
      - application/json
      description: Cron job'ın çalışıp çalışmadığını kontrol eder
      produces:
      - application/json
      responses:
        "200":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.CronStatusResponse'
      summary: Cron job durumunu getir
      tags:
      - cron
  /cron/stop:
    post:
      consumes:
      - application/json
      description: Mesaj gönderme cron job'ını durdurur
      produces:
      - application/json
      responses:
        "200":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.CronMessageResponse'
      summary: Cron job'ı durdur
      tags:
      - cron
  /messages:
    get:
      consumes:
      - application/json
      description: Veritabanındaki tüm mesajları getirir
      produces:
      - application/json
      responses:
        "200":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.MessagesResponse'
        "500":
          description: Sunucu hatası
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Tüm mesajları getir
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Yeni bir mesaj oluşturur ve veritabanına kaydeder
      parameters:
      - description: Mesaj bilgileri
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Başarılı yanıt
          schema:
            $ref: '#/definitions/handlers.MessageResponse'
        "400":
          description: Geçersiz istek
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Yeni mesaj oluştur
      tags:
      - messages
swagger: "2.0"
