basePath: /api
definitions:
  handlers.CreateMessageRequest:
    properties:
      content:
        description: Message content
        example: Hello, your order is being prepared.
        type: string
      phone:
        description: Phone number
        example: "+905551234567"
        type: string
    type: object
  handlers.CronLogsResponse:
    properties:
      data:
        description: Cron logs
        items:
          $ref: '#/definitions/models.CronLog'
        type: array
      status:
        description: Operation status
        example: success
        type: string
    type: object
  handlers.CronMessageResponse:
    properties:
      message:
        description: Operation message
        example: Cron started
        type: string
      status:
        description: Operation status
        example: success
        type: string
    type: object
  handlers.CronStatusResponse:
    properties:
      is_running:
        description: Cron job running status
        example: true
        type: boolean
      status:
        description: Operation status
        example: success
        type: string
    type: object
  handlers.ErrorResponse:
    properties:
      code:
        description: Error code
        example: CONTENT_REQUIRED
        type: string
      message:
        description: Error message
        example: Content field required
        type: string
      status:
        description: Operation status
        example: failed
        type: string
    type: object
  handlers.MessageResponse:
    properties:
      data:
        allOf:
        - $ref: '#/definitions/models.Message'
        description: Message data
      status:
        description: Operation status
        example: success
        type: string
    type: object
  handlers.MessagesResponse:
    properties:
      data:
        description: Message list
        items:
          $ref: '#/definitions/models.Message'
        type: array
      status:
        description: Operation status
        example: success
        type: string
    type: object
  models.CronLog:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      message_ids:
        description: Comma separated message IDs
        type: string
      messages_count:
        type: integer
      operation:
        description: START, STOP, UPDATE
        type: string
      status:
        description: Success or Failure
        type: boolean
    type: object
  models.Message:
    properties:
      content:
        type: string
      created_at:
        type: string
      id:
        type: integer
      message_id:
        type: string
      phone:
        type: string
      status:
        type: boolean
      updated_at:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: destek@example.com
    name: API Destek
  description: This API is used for message sending and management operations.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Fiber Message API
  version: "1.0"
paths:
  /cron/logs:
    get:
      consumes:
      - application/json
      description: Retrieves the cron job execution logs
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.CronLogsResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get cron logs
      tags:
      - cron
  /cron/start:
    post:
      consumes:
      - application/json
      description: Starts the message sending cron job
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.CronMessageResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Start cron job
      tags:
      - cron
  /cron/status:
    get:
      consumes:
      - application/json
      description: Checks if the cron job is running
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.CronStatusResponse'
      summary: Get cron job status
      tags:
      - cron
  /cron/stop:
    post:
      consumes:
      - application/json
      description: Stops the message sending cron job
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.CronMessageResponse'
      summary: Stop cron job
      tags:
      - cron
  /messages:
    get:
      consumes:
      - application/json
      description: Retrieves messages from database where status is true (sent)
      produces:
      - application/json
      responses:
        "200":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.MessagesResponse'
        "500":
          description: Server error
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Get all sent messages
      tags:
      - messages
    post:
      consumes:
      - application/json
      description: Creates a new message and saves it to the database
      parameters:
      - description: Message information
        in: body
        name: message
        required: true
        schema:
          $ref: '#/definitions/handlers.CreateMessageRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Successful response
          schema:
            $ref: '#/definitions/handlers.MessageResponse'
        "400":
          description: Invalid request
          schema:
            $ref: '#/definitions/handlers.ErrorResponse'
      summary: Create new message
      tags:
      - messages
swagger: "2.0"
